### PR TITLE
Fix type instabilities

### LINKED ISSUE #28: Improve names of variables
After starting the creation of some examples for Huginn, I'm realizing that some variable names might be confusing. The following should be updated:

For `SimulationParameters`:
- `velocities` should be changed to `download_velocities`, in order to make it clearer that it controls the download of the large ice velocity files (which are skipped during CI). 
- `working_dir` should be renamed or changed, since there is a variable with the same name in `OGGMParameters`. 

I will update this list if I come up with more.

### LINKED ISSUE #128: Use CFTime.jl to map duration to date of netcdf
Currently we are manually parsing the netcdf metadata to map a duration to a date. However, https://github.com/JuliaGeo/CFTime.jl is exactly what we are looking for. See for example https://github.com/JuliaGeo/CFTime.jl?tab=readme-ov-file#example

### LINKED ISSUE #130: Replace RasterStack by a dedicated struct
Currently we rely on `RasterStack` to store the raw climate data. However, the amount of data to store is very limited and `RasterStack` introduces type instability. We should get rid of it in `Climate2D` and store everything in a type stable way by creating dedicated structs.

### PR DESCRIPTION
**Pull request by albangossard**
This is the last PR of a long series to ensure type stability.
I replaced the `RasterStacks` in `Climate2D` by a dedicated structure that holds exactly the same information as suggested in https://github.com/ODINN-SciML/Sleipnir.jl/issues/130. That way the code is type stable.

I also took profit of that PR to address several issues:
- https://github.com/ODINN-SciML/Sleipnir.jl/issues/128 -> computation of the datetime offsets
- https://github.com/ODINN-SciML/Sleipnir.jl/issues/28 -> change the name of `velocities` to `use_velocities`

Fixes #130 #128 #28 

Follow-up PRs:
- https://github.com/ODINN-SciML/Muninn.jl/pull/31
- https://github.com/ODINN-SciML/Huginn.jl/pull/98
- https://github.com/ODINN-SciML/ODINN.jl/pull/357

### CODE REVIEW

**Comment by JordiBolibar** [comment]
Isn't there a way to have the code type stable while keeping it a `RasterStack`? I'm not getting why we need to create a new type. Can't we pass a `RasterStack` as a parametric type to fix it?

If it's the only solution alright, but otherwise I think it's still nice to keep all the functionalities of dataset processing from Rasters.jl. Especially in the future, if we try to process climate data in more complex ways, we'll have to manually implement any functionality we want.

**Comment by albangossard** [comment]
> Isn't there a way to have the code type stable while keeping it a RasterStack? I'm not getting why we need to create a new type. Can't we pass a RasterStack as a parametric type to fix it?

I'll give it a try, if it's possible I agree that's the best solution.

**Comment by albangossard** [comment]
@JordiBolibar I was able to put back the `RasterStack` and parametrize the types properly. We have gained in type stability, and in particular the functions called in the MB callback are now type stable.

File: src/glaciers/glacier/Glacier2D.jl [hunk 1]
```diff
@@ -43,13 +43,13 @@ manually, but rather through the `initialize_glaciers` function.
 - `cenlon::F`: Longitude of the glacier center.
 - `cenlat::F`: Latitude of the glacier center.
 - `params_projection::Dict{String, Float64}`: Projection parameters that allows mapping the regional grid to global WGS84 coordinates.
-- `thicknessData::Union{ThicknessData, Nothing}`: Thickness data structure that is used to store the reference values.
-- `velocityData::Union{SurfaceVelocityData, Nothing}`: Surface velocity data structure that is used to store the reference values.
+- `thicknessData::THICKDATA`: Thickness data structure that is used to store the reference values.
+- `velocityData::SURFVELDATA`: Surface velocity data structure that is used to store the reference values.
 """
-mutable struct Glacier2D{F <: AbstractFloat, I <: Integer} <: AbstractGlacier
+mutable struct Glacier2D{F <: AbstractFloat, I <: Integer, CLIM <: Climate2D, THICKDATA <: Union{<: ThicknessData, Nothing}, SURFVELDATA <: Union{<: SurfaceVelocityData, Nothing}} <: AbstractGlacier
```
Comment (JordiBolibar) [inline src/glaciers/glacier/Glacier2D.jl:49]: Doesn't this `Union` produce any issues with type stability?

File: test/results.jl [hunk 2]
```diff
@@ -24,11 +24,11 @@ function results_default(; save_refs::Bool = false, useDatacube::Bool = false)
     if useDatacube
         fakeRasterStack = fake_interpolated_datacube()
         glaciers = initialize_glaciers(rgi_ids, params; velocityDatacubes=Dict{String, RasterStack}(rgi_ids[1] => fakeRasterStack))
-        # JET.@test_opt broken=true target_modules=(Sleipnir,) initialize_glaciers(rgi_ids, params; velocityDatacubes=Dict{String, RasterStack}(rgi_ids[1] => fakeRasterStack)) # For the moment this is not type stable because of the readings (type of CSV files and RasterStack cannot be determined at compilation time)
+        JET.@test_opt broken=true target_modules=(Sleipnir,) initialize_glaciers(rgi_ids, params; velocityDatacubes=Dict{String, RasterStack}(rgi_ids[1] => fakeRasterStack)) # For the moment this is not type stable because of the readings (type of CSV files and RasterStack cannot be determined at compilation time)
```
Comment (JordiBolibar) [inline test/results.jl:27]: I guess type stability here is not super critical, because we don't need to differentiate this, right?

**Review by JordiBolibar — APPROVED** [review]
Just a couple of comments. Great work!

File: test/results.jl (hunk 2 above)
Comment (albangossard) [reply test/results.jl:27]: Yes exactly, once this function has been executed, types are properly defined.
